-- Differences to data.sql:
--  Outputs far fewer variables
--  Uses vaso_flg to say yes/no to vasopressor usage

--FINAL QUERY (ish)
select
  co.subject_id, co.hadm_id, co.icustay_id

  , co.initial_aline_flg -- always 0, we remove patients admitted w/ aline
  , co.aline_flg
  , co.aline_time_day
  , co.icu_los_day
  , co.hospital_los_day
  , co.age
  , co.gender_num

  , ed.weight_first
  , ed.height_first
  , ed.bmi

  , co.service_unit
  , co.service_num

  , co.icustay_intime
  , co.day_icu_intime -- day of week, text
  , co.day_icu_intime_num -- day of week, numeric (0=Sun, 6=Sat)
  , co.hour_icu_intime -- hour of ICU admission (24 hour clock)
  , co.icustay_outtime

  , co.hosp_exp_flg
  , co.icu_exp_flg
  , co.mort_day -- days from ICU admission to mortality, if they died
  , co.day_28_flg -- 1/0 whether the patient died 28 days after *ICU* admission
  , co.mort_day_censored -- for patients who survived, has imputed censored days
  , co.censor_flg

  , co.vent_flg
  , co.vent_1st_12hr
  , co.vent_1st_24hr
  , co.vent_b4_aline -- yes/no ventilated before a-line insertion
  , co.vent_day -- number of fractional days on a ventilator
  , co.vent_free_day -- number of fractional days *not* on a ventilator

  , angus.angus as sepsis_flg

    -- labs!
    , labs.hct_med
    , labs.hct_lowest
    , labs.hct_highest
    , labs.hct_abnormal_flg

    , labs.wbc_first, labs.wbc_abnormal_flg
    , labs.hgb_first, labs.hgb_abnormal_flg
    , labs.platelet_first, labs.platelet_abnormal_flg
    , labs.sodium_first, labs.sodium_abnormal_flg
    , labs.potassium_first, labs.potassium_abnormal_flg
    , labs.tco2_first, labs.tco2_abnormal_flg
    , labs.chloride_first, labs.chloride_abnormal_flg
    , labs.bun_first, labs.bun_abnormal_flg
    , labs.creatinine_first, labs.creatinine_abnormal_flg

from aline_cohort co
-- The following tables are generated by code in the mimic-code repository
left join angus_sepsis angus
  on co.hadm_id = angus.hadm_id
-- The following tables are generated by code within this repository
left join aline_echodata ed
  on co.icustay_id = ed.icustay_id
left join aline_vaso_flg vaso
  on co.icustay_id = vaso.icustay_id
left join aline_labs labs
  on co.hadm_id = labs.hadm_id
where coalesce(angus.angus,0) = 0 -- no septic patients
and coalesce(vaso.vaso_flg,0) = 0 -- never given vasopressors in the ICU
order by co.icustay_id;

-- The remaining exclusion criteria are applied in cohort.sql
