
--FINAL QUERY (ish)
select
  co.subject_id, co.hadm_id, co.icustay_id
  , co.icustay_intime
  , co.initial_aline_flg -- always 0, we remove patients admitted w/ aline
  , co.aline_flg
  , co.aline_time_day
  , co.icu_los_day
  , co.hospital_los_day
  , co.age
  , co.gender_num

  , ed.weight_first
  , ed.height_first
  , ed.bmi

  -- , s2.sapsii as sapsii_first -- NOTE: wasn't used in original mimic-ii study
  , s1.saps as sapsi_first
  , so.sofa as sofa_first
  , co.service_unit
  , co.service_num
  , co.icustay_outtime

  , co.day_icu_intime -- day of week, text
  , co.day_icu_intime_num -- day of week, numeric (0=Sun, 6=Sat)
  , co.hour_icu_intime -- hour of ICU admission (24 hour clock)
  , co.hosp_exp_flg
  , co.icu_exp_flg
  , co.mort_day -- days from ICU admission to mortality, if they died
  , co.day_28_flg -- 1/0 whether the patient died 28 days after *ICU* admission
  , co.mort_day_censored -- for patients who survived, has imputed censored days
  , co.censor_flg

  , co.vent_flg
  , co.vent_1st_12hr
  , co.vent_1st_24hr
  , co.vent_b4_aline -- yes/no ventilated before a-line insertion
  , co.vent_day -- number of fractional days on a ventilator
  , co.vent_free_day -- number of fractional days *not* on a ventilator

  , vaso.vaso_flg
  -- , vaso.vaso_start_day
  -- , vaso.vaso_free_day
  , vaso.vaso_day -- number of fractional days on vasopressors
  , vaso.vaso_free_day -- number of fractional days *not* on vasopressors
  , vaso.vaso_1st_3hr_flg
  , vaso.vaso_1st_6hr_flg
  , vaso.vaso_1st_12hr_flg
  , vaso.vaso_b4_aline

  -- , an.anes_start_day
  , an.anes_flg
  , an.anes_day
  , an.anes_free_day
  , an.anes_b4_aline

  , angus.angus as sepsis_flg

  , icd.chf as chf_flg
  , icd.afib as afib_flg
  , icd.renal as renal_flg
  , icd.liver as liver_flg
  , icd.copd as copd_flg
  , icd.cad as cad_flg
  , icd.stroke as stroke_flg
  , icd.malignancy as mal_flg
  , icd.respfail as resp_flg

  -- , icd.endocarditis
  -- , icd.ards as ards_flg
  -- , icd.pneumonia as pneumonia_flg

  -- vital sign value just preceeding ventilation
  , vi.map as map_1st
  , vi.heartrate as hr_1st
  , vi.temperature as temp_1st
  , vi.spo2 as spo2_1st
  -- , vi.cvp

  -- labs!
  , labs.hct_med
  , labs.hct_lowest
  , labs.hct_highest
  , labs.hct_abnormal_flg

  , labs.wbc_first, labs.wbc_abnormal_flg
  , labs.hgb_first, labs.hgb_abnormal_flg
  , labs.platelet_first, labs.platelet_abnormal_flg
  , labs.sodium_first, labs.sodium_abnormal_flg
  , labs.potassium_first, labs.potassium_abnormal_flg
  , labs.tco2_first, labs.tco2_abnormal_flg
  , labs.chloride_first, labs.chloride_abnormal_flg
  , labs.bun_first, labs.bun_abnormal_flg
  , labs.creatinine_first, labs.creatinine_abnormal_flg
  -- , labs.glucose_first, labs.glucose_abnormal_flg
  -- , labs.calcium_first, labs.calcium_abnormal_flg
  -- , labs.magnesium_first, labs.magnesium_abnormal_flg
  -- , labs.phosphate_first, labs.phosphate_abnormal_flg
  -- , labs.ast_first, labs.AST_abnormal_flg
  -- , labs.alt_first, labs.ALT_abnormal_flg
  -- , labs.ldh_first, labs.LDH_abnormal_flg
  -- , labs.bilirubin_first, labs.bilirubin_abnormal_flg
  -- , labs.alp_first, labs.ALP_abnormal_flg
  -- , labs.albumin_first, labs.albumin_abnormal_flg
  -- , labs.tropt_first, labs.tropt_abnormal_flg
  -- , labs.ck_first, labs.CK_abnormal_flg
  -- , labs.ntbnp_first, labs.NTBNP_abnormal_flg
  -- , labs.lactate_first, labs.lactate_abnormal_flg
  -- , labs.svo2_first


  -- TODO: blood gases
  -- , po2_first
  -- , po2_first_coded
  -- , po2_abnormal_flg
  -- , pco2_first
  -- , pco2_first_coded
  -- , pco2_abnormal_flg

  -- , coalesce(abg.abg_count,0) as abg_count
  -- , coalesce(vbg.vbg_count,0) as vbg_count
  -- , coalesce(abg.abg_count,0)+coalesce(vbg.vbg_count,0) as bg_total


  -- TODO: total fluid balance at the end of day 1, etc
  --   , fluid.fluid_day_1
  --   , fluid.fluid_day_2
  --   , fluid.fluid_day_3
  --   , fluid.fluid_3days_raw
  --   , fluid.fluid_3days_clean
  --   , IV.IV_day_1
  --   , IV.IV_day_2
  --   , IV.IV_day_3
  --   , IV.IV_3days_raw
  --   , IV.IV_3days_clean
  --   , rbc_day_1
  --   , rbc_total

  -- code status flags
  -- , cs.dnr
  -- , cs.cmo
  -- , cs.dncpr
  -- , cs.dni
  -- , cs.fullcode

  -- admitted to the ICU as DNR
  , cs.dnr_adm_flg

  -- switched from something else to DNR
  , cs.dnr_switch_flg
  -- switched from something else to CMO
  , cs.cmo_switch_flg
  -- switched from something else to either DNR or CMO
  , cs.dnr_cmo_switch_flg

from aline_cohort co
-- The following tables are generated by code in the mimic-code repository
left join saps s1
  on co.icustay_id = s1.icustay_id
left join sapsii s2
  on co.icustay_id = s2.icustay_id
left join sofa so
  on co.icustay_id = so.icustay_id
left join angus_sepsis angus
  on co.hadm_id = angus.hadm_id
-- The following tables are generated by code within this repository
left join aline_echodata ed
  on co.icustay_id = ed.icustay_id
left join aline_vaso vaso
  on co.icustay_id = vaso.icustay_id
left join aline_vaso_flg vaso_flg
  on co.icustay_id = vaso_flg.icustay_id
left join aline_anaesthesia an
  on co.icustay_id = an.icustay_id
left join aline_icd icd
  on co.hadm_id = icd.hadm_id
left join aline_vitals vi
  on co.hadm_id = vi.hadm_id
left join aline_labs_all labs
  on co.hadm_id = labs.hadm_id
left join aline_codestatus cs
  on co.icustay_id = cs.icustay_id
where coalesce(angus.angus,0) = 0 -- no septic patients
and coalesce(vaso_flg.vaso_flg,0) = 0 -- never given vasopressors in the ICU
order by co.icustay_id

-- The remaining exclusion criteria are applied in cohort.sql
